[package]
name = "irc2torrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10.42", features = ["vendored"] }
openssl-sys = { version = "0.9.77", features = ["vendored"] }
irc = "0.15.0"
futures = "0.3.25"
tokio = { version = "1.21.2", features = ["full"] }
failure = "0.1.8"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["json"] }
base64 = "0.13.1"
dxr = "0.5.0"
anyhow = "1.0.66"
toml = "0.5.9"
serde = "1.0.147"
serde_derive = "1.0.147"
directories = "4.0.1"