name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{matrix.config.os}}

    strategy:
      matrix:
        config:
#          - { name: "macOS Dev Build universal", artifact: "macOS-universal.dmg", os: macos-latest }
          - { name: "Linux Dev Build arm64", artifact: "linux-dev-arm64.tar.gz", os: ubuntu-latest }
#          - { name: "Linux Dev Build x64", artifact: "linux-dev-x64.tar.gz", os: ubuntu-latest }
#          - { name: "Windows Latest x64", artifact: "Windows-x64.zip", os: windows-latest, environment_script: "%programfiles(x86)%\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat" }

    steps:
    - uses: actions/checkout@v3
    - name: Install build target
      run: cargo install -f cross
    - name: Build-linux arm64
      if: startsWith(matrix.config.os, 'ubuntu') && endsWith(matrix.config.name, 'arm64')
      run: |
        cross build --release --verbose --target aarch64-unknown-linux-gnu
        ls -lah target/aarch64-unknown-linux-gnu
        ls -lah target/release
#    - name: Run tests
#      run: cross test --verbose
