name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{matrix.config.os}}

    strategy:
      matrix:
        config:
#          - { name: "macOS Dev Build universal", artifact: "macOS-universal.dmg", os: macos-latest }
          - { name: "Linux Dev Build arm64", artifact: "linux-dev-arm64.tar.gz", os: ubuntu-latest }
#          - { name: "Linux Dev Build x64", artifact: "linux-dev-x64.tar.gz", os: ubuntu-latest }
#          - { name: "Windows Latest x64", artifact: "Windows-x64.zip", os: windows-latest, environment_script: "%programfiles(x86)%\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat" }

    steps:
    - uses: actions/checkout@v3
    - name: Install build target
      run: cargo install -f cross
    - name: Build-linux arm64
      if: startsWith(matrix.config.os, 'ubuntu') && endsWith(matrix.config.name, 'arm64')
      run: |
        cross build --release --verbose --target aarch64-unknown-linux-gnu
        ls -lah target/aarch64-unknown-linux-gnu/release
        mkdir irc2torrent
        cp target/aarch64-unknown-linux-gnu/release/irc2torrent irc2torrent/irc2torrent
        cp irc.defaults.toml irc2torrent/irc.defaults.toml
        cp options.toml irc2torrent/options.toml
        tar -zcvf ${{ matrix.config.artifact }} irc2torrent/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.config.artifact }}
        path: ${{ matrix.config.artifact }}
    - name: "Create Release"
      uses: "ncipollo/release-action@v1"
      with:
        token: "${{ secrets.UPLOAD_TOKEN }}"
        allowUpdates: true
        tag: "latest"
        prerelease: true
        replacesArtifacts: true
        generateReleaseNotes: true
        name: "Development Build"
        artifacts: ${{ matrix.config.artifact }}
#        ls -lah target/release/build
#    - name: Run tests
#      run: cross test --verbose
